# Generated by Django 4.0 on 2022-01-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('owner', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('orderplaced', 'orderplaced'), ('cancelled', 'cancelled'), ('dispatched', 'dispatched'), ('intransmit', 'intransmit'), ('delivered', 'delivered')], default='orderplaced', max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expected_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
